version: '3.8'

services:

  bot:
    build: ./bot
    command: python bot/main.py

    env_file:
      - bot/.env_bot

    volumes:
      - .:/bot
    depends_on:
      - db
      - redis
    restart: always


  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always


  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/posgresql/data/

    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf

    env_file:
      - bot/.env_bot


volumes:
  postgres_data:
