services:

  bot:
    build: ./bot
    command: python bot/main.py
    env_file:
      - /bot/.env_bot
    volumes:
      - .:/bot
    depends_on:
      - db
      - redis
    restart: always
    networks:
      - deploy_network

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app
      - images_data:/bot/images/
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    networks:
      - deploy_network

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/posgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always
    networks:
      - deploy_network


  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    env_file:
      - bot/.env_bot
    networks:
      - deploy_network


volumes:
  postgres_data:
  redis_data:
  images_data:

networks:
  deploy_network:
    driver: bridge