# Generated by Django 5.1.7 on 2025-03-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(max_length=250, null=True, upload_to='bot/images', verbose_name='Изображение'),
        ),
    ]
