# Generated by Django 5.1.7 on 2025-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(max_length=250, null=True, upload_to='bot\\images', verbose_name='Изображение'),
        ),
    ]
